# Generated by Django 4.1.4 on 2023-10-07 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
