# Generated by Django 4.1.4 on 2023-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="code",
        ),
        migrations.AddField(
            model_name="project",
            name="project_file",
            field=models.FileField(default="test.py", upload_to="project_files/"),
        ),
        migrations.DeleteModel(
            name="ProjectFile",
        ),
    ]
