# Generated by Django 4.2.6 on 2023-10-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_project_code_project_project_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Игра', 'Сайт'), ('Приложение', 'Другое...')], default='DEFAULT_VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, default='test.py', help_text='Выберите несколько файлов', max_length=255, null=True, upload_to='files/', verbose_name='Files'),
        ),
    ]
