# Generated by Django 4.2.6 on 2023-10-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_project_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_file2',
            field=models.FileField(default='test.py', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file3',
            field=models.FileField(default='test.py', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file4',
            field=models.FileField(default='test.py', upload_to='files/'),
        ),
    ]
