# Generated by Django 4.2.6 on 2023-10-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_project_file2_project_project_file3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Game', 'Игра'), ('Sait', 'Сайт'), ('App', 'Приложение'), ('Another one', 'Другое...')], default='DEFAULT_VALUE', max_length=100),
        ),
    ]
